### ISSUE TITLE
Syllabification does not work with double letter consonants

### ISSUE THREAD

**Issue by anefta** [PicusZeus/modern_greek_accentuation#1]
First, you have done a great job here! 

Second, syllabification does not work with double letter consonants for modern Greek.
Eg. "μαγκώνω" - The correct syllables are `[ 'μα' , 'γκώ', 'νω'].`  So, the consonant complex "**γκ**" is pronounced like "g", that means one consonant.

`modern_greek_syllabify('μαγκώνω')` outputs wrong `['μαγ', 'κώ', 'νω']`.

In your code I did not see anywhere to list two letter consonants like "μπ, ντ, γκ, γγ, ββ etc.
Perhaps I could help.

**Comment by PicusZeus** [comment]
Well, you're right. I developed it from Ancient Greek syllabification module, where these double consonants actually are divided in syllabification, so it was something I didn't actually thought about, especially that this module was created mainly for my modern-greek-inflexion library, where the correct division of double consonants actually doesn't change anything. If you feel like it, you can modify the code (add also tests) and make a pull request. And if not I will try to fix it when I find time.

**Comment by PicusZeus** [comment]
At last I found a moment to fix the issue. Now it works correctly as far as syllabification is concerned
